### ISSUE TITLE
First run with a manual last run date of 10-Nov-2019 22:00:00, errors out.

### ISSUE THREAD

**Issue by MaybeThisIsRu** [gcflames5/ynab-splitwise-integration#3]
I followed all the steps as per the wiki. With a last run date of `never`, YNAB API was erroring out.

Changing the date to something recent so the transactions to write would be fewer, I am consistently receiving the following error:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.github.gclfames5.Main.main(Main.java:125)
```

`java -version`:
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```

**Comment by gcflames5** [comment]
Interesting, do any of the memos in your Splitwise account have the string "sw_uuid" in them?

**Comment by MaybeThisIsRu** [comment]
I haven't been receiving this error consistently, so frankly it'd be hard to diagnose right now. I am not from a Java background - would you have any tips on logging data whenever I face this again to help you on this?

When the app writes to YNAB successfully, yes, I can see `sw_uuid` in the transaction memos.

**Comment by gcflames5** [comment]
Should be fixed in the latest version. Commit `0acd2d4315214061d70109a1c485427a7235a336`
